name: build all platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build_native:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        so_64: [OFF, ON]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6

    - name: Configure CMake
      run: cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DSO_64=${{ matrix.so_64 }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest --build-config ${{ env.BUILD_TYPE }} --output-on-failure

    - name: Upload native artifact
      uses: actions/upload-artifact@v6
      with:
        name: SoFixer-${{ matrix.os }}-${{ matrix.so_64 }}
        path: ${{ github.workspace }}/build/SoFixer*
        if-no-files-found: error

  build_android_arm64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup Android NDK
      id: setup-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r27c

    - name: Configure CMake(Android arm64-v8a)
      run: >
        cmake -S ${{ github.workspace }}
        -B ${{ github.workspace }}/build-android-arm64
        -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        -DSO_64=ON
        -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake
        -DANDROID_ABI=arm64-v8a
        -DANDROID_PLATFORM=android-21

    - name: Build(Android arm64-v8a)
      run: cmake --build ${{ github.workspace }}/build-android-arm64 --config ${{ env.BUILD_TYPE }}

    - name: Upload Android artifact
      uses: actions/upload-artifact@v6
      with:
        name: SoFixer-Android-arm64
        path: ${{ github.workspace }}/build-android-arm64/SoFixer64
        if-no-files-found: error
